server:
  port: 443
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
info:
  component: Edge Server
eureka:
  instance:
#    prefer-ip-address: true
    hostname: localhost
    secure-port: ${server.port}
    non-secure-port: 80
    secure-port-enabled: true
    non-secure-port-enabled: false
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 3
    status-page-url: https://${eureka.instance.hostname}/info
    health-check-url: https://${eureka.instance.hostname}/health
    home-page-url: https://${eureka.instance.hostname}/
  client:
    service-url:
      defaultZone: https://localhost:8761/discoveryServer/eureka/
#    initial-instance-info-replication-interval-seconds: 3