server:
  port: 80
spring.profiles.active: ssl,eureka-ssl
info:
  component: Edge Server
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true
    hostname: localhost
    secure-port: ${server.port}
    non-secure-port: ${server.port}
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    initial-instance-info-replication-interval-seconds: 3
# TODO: until finding a better solution, disable hystrix command timeout in edge server. See https://github.com/spring-cloud/spring-cloud-netflix/issues/321#issuecomment-97727313
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
zuul:
  ignoredServices: '*'
  routes:
    # NOTE regarding 'sensitiveHeaders' properties:
    #      By default, Zuul will strip the 'Cookie', 'Set-Cookie', and 'Authorization' HTTP headers
    #      from incoming HTTP requests before forwarding them to the appropriate downstream services.
    #      Since UAA and UAA-secured services require the 'Authorization' header to work, you must
    #      set the 'sensativeHeaders' property for secured routes to only strip out 'Cookie' and
    #      'Set-Cookie' headers.
    #
    #      For more info, see: http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_cookies_and_sensitive_headers
    pp-ui:
      path: /pp-ui/**
    admin-ui:
      path: /admin-ui/**
    pep:
      path: /pep/**
      # Override Zuul default:
      sensitiveHeaders: Cookie,Set-Cookie
    pcm:
      path: /pcm/**
      # Override Zuul default:
      sensitiveHeaders: Cookie,Set-Cookie
    phr:
      path: /phr/**
      # Override Zuul default:
      sensitiveHeaders: Cookie,Set-Cookie
    try-policy:
      path: /tryPolicy/**
      # Override Zuul default:
      sensitiveHeaders: Cookie,Set-Cookie
    patient-registration:
      path: /patientRegistration/**
      # Override Zuul default:
      sensitiveHeaders: Cookie,Set-Cookie
    patient-user:
      path: /patientUser/**
      # Override Zuul default:
      sensitiveHeaders: Cookie,Set-Cookie
    uaa:
      path: /uaa/**
      # Override Zuul default:
      sensitiveHeaders: Cookie,Set-Cookie
      url: https://localhost:8443/uaa
    pls:
      path: /pls/**
      url: https://localhost:8443/pls
mhc:
  edge-server:
    root-redirect-url: redirect:/pp-ui
logging:
  file: /java/MHC_LOGS/edge-server/edgeServer.log
  level:
    org.springframework.cloud.netflix: info
response:
  header:
    key: WWW-Authenticate
    value: Application driven
# secure management endpoints
management:
  security:
    enabled: true
    sessions: never
  context-path: /management
security:
  basic:
    enabled: true
    path: ${management.context-path}/**
  user:
    name: admin
    password: changeit
  require-ssl: true
  sessions: never
---
spring.profiles: ssl
server:
  port: 443
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
    ciphers: "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    enabledProtocols: "TLSv1.1,TLSv1.2"
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true
    hostname: localhost
    secure-port: ${server.port}
    non-secure-port: 80
    secure-port-enabled: true
    non-secure-port-enabled: false
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 3
    status-page-url: https://${eureka.instance.hostname}/info
    health-check-url: https://${eureka.instance.hostname}/health
    home-page-url: https://${eureka.instance.hostname}/
---
spring.profiles: eureka-ssl
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
---
spring.profiles: docker
server:
  port: 443
  ssl:
    key-store: /java/keystore/mhc.keystore
    key-store-password: changeit
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server.mhc.com:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    uaa:
      path: /uaa/**
      url: https://uaa.mhc.com:8443/uaa
    pls:
      path: /pls/**
      url: https://pls.mhc.com:8443/pls